# PROstudio copyright 2016
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++#
#                                                       #
#                Design And Developed by IZTech         #
#                     ManingTeh                         #
#                Dev: Ivo Zinenda                       #
#               Email: izinenda@outlook.com             #
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++#

name: PROstudio
title: 
description: Photograph like a PRO
keywords: "Fotografias, Galaria, Serviços, Contactos, Quem Somos"
email:
facebook: PRO-studio-899720856809832
youtube: channel/UCexlEfQRnWKdElPO_KnJjrA
twitter:
    username: Imaz_3g
url: http://zinenda.github.io/prostudio

# dev intel
author:
    name: Ivo Zinenda
    email: izinenda@outlook.com
    google: https://plus.google.com/u/0/+IvoZinenda
    
markdown: kramdown

# directories
sass:
    sass_dir: assets/_sass
    style: compressed

language_data: data.lang.%%
language_includes_dir: _i18n

gems:
    - jekyll-seo-tag